import spotipy
from spotipy.oauth2 import SpotifyClientCredentials, SpotifyOAuth
import spotipy.util as util

import pandas as pd
import time

client_id = 'f3b6b69d44b9416ca63b4788eac70bc5'
client_secret = 'b360ac0c84f04209b0ce388f2519db20'
scope = 'user-top-read playlist-modify-public'
redirect_uri = 'http://masrani.tech/'
username = 'firebreather3000'
client_credentials_manager = SpotifyClientCredentials(client_id, client_secret)
sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)
sp1 = spotipy.Spotify(auth_manager=SpotifyOAuth(username=username,scope = scope,client_id=client_id,client_secret=client_secret,redirect_uri=redirect_uri))
#code = request.args.get(['code'])
#sp.current_user_top_artists(time_range='long_term')

def getTrackIDs(user, playlist_id):
    ids = []
    playlist = sp.user_playlist(user, playlist_id)
    for item in playlist['tracks']['items']:
        track = item['track']
        ids.append(track['id'])
    return ids

def getTopArtist(index, limit):
    length = ['short_term', 'medium_term', 'long_term']
    topartist = sp1.current_user_top_artists(time_range=length[index], limit=limit)
    return topartist

def getTopSongs(index, limit):
    length = ['short_term', 'medium_term', 'long_term']
    topsongs = sp1.current_user_top_tracks(time_range=length[index], limit=limit)
    return topsongs

def generatePlaylist(name):
    sp1.user_playlist_create(user=username, name=name, description='Playlist generated by Playlistify')

def getPlaylistID():
    user_playlist = sp1.user_playlists(user=username,limit=1,offset=0)
    for item in user_playlist:
        print(item)
    playlist_Data = user_playlist['items'][0]
    print(playlist_Data)
    playlist_ID = playlist_Data['id']
    return playlist_ID
